// ─── PALETTE ────────────────────────────────────────────────────────────────
export const C = {
  bg:           "#F4F0EA",
  white:        "#FDFCFA",
  sand:         "#EDE8DF",
  sandDark:     "#DDD5C8",
  primary:      "#7C5C3E",
  primaryLight: "#9E7A58",
  primaryPale:  "#F0E8DC",
  primaryDeep:  "#4E3726",
  secondary:    "#5C7A5C",
  secondaryPale:"#E8F0E8",
  secondaryDark:"#3D5C3D",
  text:         "#2A2218",
  muted:        "#8C7B6A",
  border:       "#D8CEC0",
  green:        "#5C8C6A",  greenPale:  "#E6F2EA",
  yellow:       "#B8863A",  yellowPale: "#FBF3E2",
  red:          "#B84A3A",  redPale:    "#FBECEB",
  blue:         "#4A7A9B",  bluePale:   "#E8F2F8",
};

// ─── CONSTANTES GLOBALES ─────────────────────────────────────────────────────
export const DEFAULT_FLAT_SPEED = 9.5;
export const DEFAULT_EQUIPMENT = [
  { id: 1,  cat: "Équipement",     label: "Gilet de trail",           checked: false, actif: true,  emporte: true,  poidsG: 400 },
  { id: 2,  cat: "Équipement",     label: "T-shirt course",           checked: false, actif: true,  emporte: true,  poidsG: 150 },
  { id: 3,  cat: "Équipement",     label: "T-shirt change × 2",       checked: false, actif: false, emporte: false, poidsG: 300 },
  { id: 4,  cat: "Équipement",     label: "Short / cuissard",         checked: false, actif: true,  emporte: true,  poidsG: 120 },
  { id: 5,  cat: "Équipement",     label: "Chaussettes",              checked: false, actif: true,  emporte: true,  poidsG: 60  },
  { id: 6,  cat: "Équipement",     label: "Chaussures de trail",      checked: false, actif: true,  emporte: true,  poidsG: 600 },
  { id: 7,  cat: "Équipement",     label: "Bâtons",                   checked: false, actif: false, emporte: true,  poidsG: 400 },
  { id: 8,  cat: "Équipement",     label: "Veste imperméable",        checked: false, actif: true,  emporte: true,  poidsG: 250 },
  { id: 9,  cat: "Équipement",     label: "Casquette / buff",         checked: false, actif: true,  emporte: true,  poidsG: 60  },
  { id: 10, cat: "Équipement",     label: "Lampe frontale + piles",   checked: false, actif: true,  emporte: true,  poidsG: 120 },
  { id: 11, cat: "Équipement",     label: "Couverture de survie",     checked: false, actif: true,  emporte: true,  poidsG: 80  },
  { id: 12, cat: "Équipement",     label: "Sifflet",                  checked: false, actif: true,  emporte: true,  poidsG: 20  },
  { id: 13, cat: "Ravitaillement", label: "Pâtes de fruits sucrées",  checked: false, actif: false, emporte: true,  poidsG: 0   },
  { id: 14, cat: "Ravitaillement", label: "Pâtes de fruits salées",   checked: false, actif: false, emporte: true,  poidsG: 0   },
  { id: 15, cat: "Ravitaillement", label: "Barres de céréales",       checked: false, actif: false, emporte: true,  poidsG: 0   },
  { id: 16, cat: "Ravitaillement", label: "Gels énergétiques",        checked: false, actif: false, emporte: true,  poidsG: 0   },
  { id: 17, cat: "Ravitaillement", label: "Gourde / flasques",        checked: false, actif: true,  emporte: true,  poidsG: 200 },
  { id: 18, cat: "Ravitaillement", label: "Sel / électrolytes",       checked: false, actif: false, emporte: true,  poidsG: 50  },
  { id: 19, cat: "Divers",         label: "Dossard + épingles",       checked: false, actif: true,  emporte: true,  poidsG: 20  },
  { id: 20, cat: "Divers",         label: "Téléphone chargé",         checked: false, actif: true,  emporte: true,  poidsG: 180 },
  { id: 21, cat: "Divers",         label: "Crème anti-frottements",   checked: false, actif: true,  emporte: true,  poidsG: 50  },
  { id: 22, cat: "Divers",         label: "Brosse à dents / hygiène", checked: false, actif: false, emporte: false, poidsG: 0   },
  { id: 23, cat: "Divers",         label: "Vêtements post-course",    checked: false, actif: false, emporte: false, poidsG: 0   },
  { id: 24, cat: "Préparation",    label: "Strapping pieds / genoux", checked: false, actif: false, emporte: true,  poidsG: 30  },
  { id: 25, cat: "Préparation",    label: "Crème solaire",            checked: false, actif: false, emporte: true,  poidsG: 50  },
  { id: 26, cat: "Préparation",    label: "Vaseline / nez crème",     checked: false, actif: false, emporte: true,  poidsG: 30  },
  { id: 27, cat: "Préparation",    label: "Carte d'identité",         checked: false, actif: true,  emporte: true,  poidsG: 10  },
  { id: 28, cat: "Préparation",    label: "Certificat médical",       checked: false, actif: false, emporte: true,  poidsG: 10  },
  { id: 29, cat: "Préparation",    label: "Chargeur portable",        checked: false, actif: false, emporte: false, poidsG: 200 },
  { id: 30, cat: "Préparation",    label: "Collants de compression",  checked: false, actif: false, emporte: false, poidsG: 150 },
];

export const PREP_TIMELINE = [
  { id: "j14_chaussures",  phase: "J−14", cat: "Équipement",  label: "Vérifier les chaussures (semelles > 2mm, couture OK)" },
  { id: "j14_sac",         phase: "J−14", cat: "Équipement",  label: "Tester le sac / gilet chargé sur une sortie" },
  { id: "j14_gels",        phase: "J−14", cat: "Nutrition",   label: "Commander gels et produits manquants" },
  { id: "j14_logement",    phase: "J−14", cat: "Logistique",  label: "Réserver logement à proximité du départ" },
  { id: "j14_transport",   phase: "J−14", cat: "Logistique",  label: "Organiser transport aller-retour" },
  { id: "j7_gps",          phase: "J−7",  cat: "Équipement",  label: "Charger GPS et batteries externes, tester la montre" },
  { id: "j7_meteo",        phase: "J−7",  cat: "Logistique",  label: "Vérifier la météo, adapter l'équipement" },
  { id: "j7_drop",         phase: "J−7",  cat: "Logistique",  label: "Préparer les drop-bags si ultra long" },
  { id: "j7_inscrip",      phase: "J−7",  cat: "Logistique",  label: "Confirmer inscription, récupération du dossard" },
  { id: "h48_flasques",    phase: "H−48", cat: "Équipement",  label: "Test remplissage flasques, vérifier étanchéité" },
  { id: "h48_nutrition",   phase: "H−48", cat: "Nutrition",   label: "Préparer et peser la nutrition complète" },
  { id: "h48_drop2",       phase: "H−48", cat: "Logistique",  label: "Finaliser drop-bags, étiqueter clairement" },
  { id: "h48_route",       phase: "H−48", cat: "Logistique",  label: "Planifier itinéraire et horaire pour le départ" },
  { id: "h24_piles",       phase: "H−24", cat: "Équipement",  label: "Piles lampe frontale 100%, charger téléphone" },
  { id: "h24_dossard",     phase: "H−24", cat: "Équipement",  label: "Épingler le dossard, vérifier le règlement" },
  { id: "h24_recup",       phase: "H−24", cat: "Logistique",  label: "Récupérer le dossard si retrait en avance" },
  { id: "h24_sommeil",     phase: "H−24", cat: "Logistique",  label: "Se coucher tôt, éviter les repas lourds" },
  { id: "h1_creme",        phase: "H−1",  cat: "Préparation", label: "Crème anti-frottements, vaseline, strapping pieds" },
  { id: "h1_check",        phase: "H−1",  cat: "Équipement",  label: "Check final sac : eau, nutrition, lampe, veste" },
  { id: "h1_solaire",      phase: "H−1",  cat: "Préparation", label: "Crème solaire si course ensoleillée" },
  { id: "h1_ravitos",      phase: "H−1",  cat: "Logistique",  label: "Confirmer plan ravitos avec l'équipe d'assistance" },
];

export const EMPTY_SETTINGS = {
  weight: 70, kcalPerKm: 65, kcalPerKmUphill: 90,
  fcMax: null, fcZone2Max: null,
  raceName: "", startTime: "07:00", raceDate: "",
  meteoLoading: false, meteoFetched: false, meteoInfo: "",
  tempC: 15, rain: false, wind: false, snow: false,
  darkMode: false,
  garminCoeff: 1, garminStats: null, kcalSource: "minetti",
  glucidesTargetGh: null,
  runnerLevel: "intermediaire",
  effortTarget: "normal",
  paceStrategy: 0,
  ravitoTimeMin: 3,
  segmentDetail: "equilibre",
  equipment: DEFAULT_EQUIPMENT,
  produits: [],
  prepChecks: {},
};

// ─── ALGOS TRAIL ─────────────────────────────────────────────────────────────
export const RUNNER_LEVELS = [
  { key: "debutant",      label: "Débutant",      coeff: 0.72, desc: "Premiers trails, objectif finisher" },
  { key: "intermediaire", label: "Intermédiaire", coeff: 0.88, desc: "Quelques courses, chrono réaliste" },
  { key: "confirme",      label: "Confirmé",      coeff: 1.00, desc: "Niveau entraîné, bonne régularité" },
  { key: "expert",        label: "Expert",        coeff: 1.12, desc: "Compétiteur, podium régional" },
];
export const TERRAIN_TYPES = [
  { key: "normal",    label: "Normal",         coeff: 1.00, desc: "Chemin balisé, single track roulant" },
  { key: "technique", label: "Technique",      coeff: 0.82, desc: "Cailloux, racines, passages délicats" },
  { key: "trestech",  label: "Très technique", coeff: 0.68, desc: "Éboulis, hors-sentier, passages engagés" },
];
